import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import type { TLayoutProps } from "@/lib/types/root.types";
import { ReduxProvider } from "@/components/providers/redux-provider";
import { SmoothScrollProvider } from "@/components/providers/smooth-scroll-provider";
import { Navbar } from "@/components/shared/navbar";
import "./globals.css";

// Font for the entire app
const montserrat = Montserrat({
  subsets: ["vietnamese"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// Metadata for the entire app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: TLayoutProps) {
  return (
    <html lang="en">
      <SmoothScrollProvider>
        <ReduxProvider>
          <body className={`${montserrat.className} bg-zinc-100`}>
            <Navbar />
            {children}
          </body>
        </ReduxProvider>
      </SmoothScrollProvider>
    </html>
  );
}
